import { openDB, type DBSchema, type IDBPDatabase } from 'idb';
import type { Bill, CheesyLine, Counter, Dish, MetaMap, MonthlyStats, Settings } from './types';
import { BUILT_IN_LINES } from '../data/cheesyLines';

export const DB_NAME = 'restobill';
export const DB_VERSION = 1;

export interface RestoDB extends DBSchema {
  menu: { key: number; value: Dish; indexes: { category: string } };
  bills: { key: string; value: Bill; indexes: { createdAt: number; monthKey: string } };
  counters: { key: string; value: Counter };
  monthlyStats: { key: string; value: MonthlyStats };
  settings: { key: string; value: Settings };
  cheesyLines: { key: number; value: CheesyLine };
  meta: { key: string; value: MetaMap[keyof MetaMap] };
}

export type DB = IDBPDatabase<RestoDB>;

export const SETTINGS_KEY = 'app';

export const DEFAULT_SETTINGS: Settings = {
  name: 'My Restaurant',
  address: '',
  phone: '',
  currencySymbol: '₹',
  receiptWidth: '80',
  roundOff: true,
};

let dbPromise: Promise<DB> | undefined;

export function getDB(): Promise<DB> {
  dbPromise ??= openDB<RestoDB>(DB_NAME, DB_VERSION, {
    upgrade(db, oldVersion, _newVersion, tx) {
      if (oldVersion < 1) {
        const menu = db.createObjectStore('menu', { keyPath: 'id', autoIncrement: true });
        menu.createIndex('category', 'category');
        const bills = db.createObjectStore('bills', { keyPath: 'billNo' });
        bills.createIndex('createdAt', 'createdAt');
        bills.createIndex('monthKey', 'monthKey');
        db.createObjectStore('counters', { keyPath: 'monthKey' });
        db.createObjectStore('monthlyStats', { keyPath: 'monthKey' });
        db.createObjectStore('settings');
        db.createObjectStore('cheesyLines', { keyPath: 'id', autoIncrement: true });
        db.createObjectStore('meta');

        void tx.objectStore('settings').put(DEFAULT_SETTINGS, SETTINGS_KEY);
        const lines = tx.objectStore('cheesyLines');
        for (const text of BUILT_IN_LINES) {
          // `id` is generated by autoIncrement.
          void lines.add({ text, builtIn: true, active: true } as CheesyLine);
        }
      }
    },
    blocked() {
      // Another tab holds an older version open.
      console.warn('Database upgrade blocked by another open tab.');
    },
    terminated() {
      dbPromise = undefined;
    },
  });
  return dbPromise;
}

/** Tests only: forget the cached connection so a fresh IndexedDB can be used. */
export async function resetDBForTests(): Promise<void> {
  if (dbPromise) (await dbPromise).close();
  dbPromise = undefined;
}
